name: VillagerStackableCuring
version: ${version}
author: spartacus04
main: me.spartacus04.stackablecuring.StackableCuring
api-version: 1.20
description: plugin to allow villagers to have stackable cures
depend: [NBTAPI]
folia-supported: true

commands:
  stackablecuring:
    description: Main command of the plugin
    usage: /stackablecuring
    aliases:
      - stackablevillagercuring

permissions:
  stackablecuring.*:
    children:
      - stackablecuring.reload
      - stackablecuring.config
  stackablecuring.reload:
    description: Allows the player to reload the plugin
    default: op
  stackablecuring.config:
    description: Allows the player to edit the config
    default: op
  stackablecuring.notifyupdate:
    description: Notifies the player when a new version is available
    default: op
